解决ts-node报错。正常执行：npx ts-node  src_gitee_api/gitee_import_repo.ts  --help
src_gitee_api/MarkupFieldUtil.ts:7:56 - error TS2769: No overload matches this call.
  Overload 1 of 4, '(iterable?: Iterable<readonly [string, MarkupFieldI]>): Map<string, MarkupFieldI>', gave the following error.
    Argument of type '(string | MarkupFieldI)[][]' is not assignable to parameter of type 'Iterable<readonly [string, MarkupFieldI]>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<(string | MarkupFieldI)[], any>' is not assignable to type 'IteratorResult<readonly [string, MarkupFieldI], any>'.
          Type 'IteratorYieldResult<(string | MarkupFieldI)[]>' is not assignable to type 'IteratorResult<readonly [string, MarkupFieldI], any>'.
            Type 'IteratorYieldResult<(string | MarkupFieldI)[]>' is not assignable to type 'IteratorYieldResult<readonly [string, MarkupFieldI]>'.
              Type '(string | MarkupFieldI)[]' is not assignable to type 'readonly [string, MarkupFieldI]'.
                Target requires 2 element(s) but source may have fewer.
  Overload 2 of 4, '(entries?: readonly (readonly [string, MarkupFieldI])[]): Map<string, MarkupFieldI>', gave the following error.
    Argument of type '(string | MarkupFieldI)[][]' is not assignable to parameter of type 'readonly (readonly [string, MarkupFieldI])[]'.
      Type '(string | MarkupFieldI)[]' is not assignable to type 'readonly [string, MarkupFieldI]'.

7     const dct:Map<MarkupFldNmTyp,MarkupFieldI>=new Map(tupleLs)