解决.ts直接运行的一个报错 ，但是后面还有更多报错，放弃ts-node了， ts-node src/main.ts
解决报错：

/app/nvm/versions/node/v18.19.1/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:7:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("chrome-launcher")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

7 import * as CL from 'chrome-launcher'